


DROP TABle Users


CREATE TABLE Users (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Email NVARCHAR(200) NOT NULL UNIQUE,
    AccessToken NVARCHAR(500) NULL UNIQUE,
    RefreshToken NVARCHAR(500) NULL UNIQUE,
    TokenExpiry NVARCHAR(500) NULL,
    LastLogin DATETIME NULL,
    Name NVARCHAR(200) NOT NULL,
    Password NVARCHAR(200) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE()
);


ALTER TABLE Users
ADD PasswordResetToken NVARCHAR(500) NULL,
    PasswordResetExpires DATETIME NULL;
    
SELECT * FROM Users