


DROP TABle Users
CREATE TABLE  Users(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Email NVARCHAR(200) NOT NULL UNIQUE,
    Name NVARCHAR(200) NOT NULL,
    Password NVARCHAR(200) NOT NULL,
    CreatedAt DATETIME DEFAULT GETDATE()
)